dsite_name: Tools of Ignorance
remote_theme: catieslaughts/minimal-toi
title: Tools of Ignorance
description: Catherine M. Slaughter<br>Dingers and Data
#logo: images_pdfs/photos/badlands_cropped.jpg
